### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by UULaCrevette** [sethpotter/BetonMultiplayer#2]
Hi, when a player watches a replay of another player, the replay appears for everyone under the name of the player watching, and not that of the player who made the replay, so this can create confusion, especially if people organize races, if someone puts on a speedrun instead of playing, it's annoying
And also, several friends and I believe that we have more freezes in the game since we put the multiplayer mod, if ever there is a way to optimize that a little more (I know that the base game contains freezes and you can't do much about it, but just in case, thank you very much)
The mod is great otherwise, congratulations!

**Comment by sethpotter** [comment]
Hi I'm glad to hear that the mod works for you and your friends. Yeah I noticed the lag issues myself. I was playing the new B-Day map with some friends and was experiencing a decent amount of freezes. I'm not sure if this is related to the latest update or this mod. Needs testing with and without the mod. It's definitely possible to optimize it some. I also would like to fix some syncing issues with it, but haven't had time. 

I am open to feature requests so feel free to write any ideas you might have. 

Regarding replays, this mod was not intended to be a complete multiplayer mod. Replays are recorded locally on the client. I would need to do some research on how replays are stored and how they are played back. I'm not sure how much effort would be involved to overhaul the current system.

I'm not opposed to fixing any of these issues at some point but I am currently focused on other projects.

Thanks again for your interest and I would love to see some of your moments using the mod. I know I've had my fair share of fun with it.
